services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: darna
      POSTGRES_PASSWORD: darna
      POSTGRES_DB: darna
    ports:
      - "5433:5432"
    volumes:
      - darna_db:/var/lib/postgresql/data

volumes:
  darna_db:
